<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Employee;
use App\Models\Seksi;
use Faker\Factory as Faker;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class EmployeeSeeder extends Seeder
{
    public function run() : void
    {

        // Mengambil Seksi id Tata Usha
        $seksi_id = DB::table('seksis')->where('nama_seksi','Sub Bagian Tata Usaha')->value('id');

        // Mengambil Seksi Penguatan Kelembagaan DAS
        $seksi_penguatan_das = DB::table('seksis')->where('nama_seksi','Penguatan Kelembagaan DAS')->value('id');

        // Mengambil Seksi RHL
        $seksi_rhl = DB::table('seksis')->where('nama_seksi','RHL')->value('id');

        // Mengambil Seksi Perencanaan dan Evaluasi DAS
        $seksi_perencaanaa_evaluasi = DB::table('seksis')->where('nama_seksi','Perencanaan dan Evaluasi DAS')->value('id');


        // Data pegawai
        $employees = [
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_id,
                'nama_pelaksana' => 'Bontor Lumbantobing, S.Hut.T., M.Sc.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'Pembina Tingkat I (IV/b)',
                'jabatan' => 'Kepala Balai',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_id,
                'nama_pelaksana' => 'Muhammad Bakri Nongko, S.E.,M.Si.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'Pembina (IV/a)',
                'jabatan' => 'Kepala Sub Bagian Tata Usaha',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_id,
                'nama_pelaksana' => 'Efendy Payuyu, S.Hut., M.Si.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'Pembina (IV/a)',
                'jabatan' => 'Analis Perencanaan Anggaran',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_id,
                'nama_pelaksana' => 'Yulia Fransiska, S.E.',
                'jenis_kelamin' => 'P',
                'pangkat_golongan' => 'Penata Tingkat I (III/d)',
                'jabatan' => 'Penata Laporan Keuangan',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_id,
                'nama_pelaksana' => 'Abdurrahman Taib',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'Penata Muda Tingkat I (III/b)',
                'jabatan' => 'Pengelola Barang Persediaan',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_id,
                'nama_pelaksana' => 'Andi Hangato Suaib',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'Penata Muda (III/a)',
                'jabatan' => 'Bendahara',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_id,
                'nama_pelaksana' => 'Kaharudin A Abdul',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'Penata Muda (III/a)',
                'jabatan' => 'Pengadministrasi Umum',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_id,
                'nama_pelaksana' => 'Sutrisno Moha',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'Penata Muda (III/a)',
                'jabatan' => 'Pengelola Keuangan',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_id,
                'nama_pelaksana' => 'Immanuel Sinaga, A.Md.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'Pengatur (II/c)',
                'jabatan' => 'Verifikator Keuangan',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_id,
                'nama_pelaksana' => 'Evan Ahmad, S.Si.',
                'jenis_kelamin' => 'P',
                'pangkat_golongan' => 'IX',
                'jabatan' => 'Pranata Komputer Ahli Pertama',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_id,
                'nama_pelaksana' => 'Nurhayati Tolinggi, S.E.',
                'jenis_kelamin' => 'P',
                'pangkat_golongan' => 'IX',
                'jabatan' => 'Pranata Hubungan Masyarakat Ahli Pertama',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_id,
                'nama_pelaksana' => 'Frizka Rahma Helingo, S.E.',
                'jenis_kelamin' => 'P',
                'pangkat_golongan' => 'IX',
                'jabatan' => 'Pranata Hubungan Masyarakat Ahli Pertama',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_id,
                'nama_pelaksana' => 'Sahlan Sukardi Massa, S.E.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'IX',
                'jabatan' => 'Pranata Hubungan Masyarakat Ahli Pertama',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_id,
                'nama_pelaksana' => 'Rahmawati Kai, S.Pd.',
                'jenis_kelamin' => 'P',
                'pangkat_golongan' => 'IX',
                'jabatan' => 'Pengelola Pengadaan Barang/Jasa Ahli Pertama',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_id,
                'nama_pelaksana' => 'Muazin Friandy Arsad, S.Kom.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'IX',
                'jabatan' => 'Pranata Komputer Ahli Pertama',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_id,
                'nama_pelaksana' => 'Riyanto A Hakim, S.Kom.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'IX',
                'jabatan' => 'Arsiparis Ahli Pertama',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_id,
                'nama_pelaksana' => 'Vivi Ainsyah Lamatenggo, S.Si',
                'jenis_kelamin' => 'P',
                'pangkat_golongan' => '',
                'jabatan' => 'PPNPN',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_id,
                'nama_pelaksana' => 'Windi Putra Hiola, S.E.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => '',
                'jabatan' => 'PPNPN',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_id,
                'nama_pelaksana' => 'Nurhayati Hapsari Uno, S.H.',
                'jenis_kelamin' => 'P',
                'pangkat_golongan' => '',
                'jabatan' => 'PPNPN',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_id,
                'nama_pelaksana' => 'Abdul Haris Beu',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => '',
                'jabatan' => 'PPNPN',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_id,
                'nama_pelaksana' => 'Tamrin Lababa',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => '',
                'jabatan' => '',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_penguatan_das,
                'nama_pelaksana' => 'Faisal Misran, S.P., M.P.W.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'Penata Tingkat I (III/d)',
                'jabatan' => 'Kepala Seksi Penguatan Kelembagaan DAS',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_penguatan_das,
                'nama_pelaksana' => 'Agus Budi Priyanto, S.Hut., M.Sc.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'Penata (III/c)',
                'jabatan' => 'Pengendali Ekosistem Hutan Ahli Muda',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_penguatan_das,
                'nama_pelaksana' => 'Wazir Tontoiyo, S.Hut.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'Penata Muda Tingkat I (III/b)',
                'jabatan' => 'Pengendali Ekosistem Hutan Ahli Pertama',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_penguatan_das,
                'nama_pelaksana' => 'Mohammad Awaluddin Hadju',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'Penata Muda Tingkat I (III/b)',
                'jabatan' => 'Pengendali Ekosistem Hutan Mahir',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_penguatan_das,
                'nama_pelaksana' => 'Kevin Agung Laksono, S.Sos.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'Penata Muda (III/a)',
                'jabatan' => 'Pengendali Ekosistem Hutan Ahli Pertama',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_penguatan_das,
                'nama_pelaksana' => 'Rahmat Frensya Baso',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'V',
                'jabatan' => 'Pengendali Ekosistem Hutan Pemula',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_penguatan_das,
                'nama_pelaksana' => 'Masitha',
                'jenis_kelamin' => 'P',
                'pangkat_golongan' => 'V',
                'jabatan' => 'Pengendali Ekosistem Hutan Pemula',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_penguatan_das,
                'nama_pelaksana' => 'Yakop Maku',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'V',
                'jabatan' => 'Pengendali Ekosistem Hutan Pemula',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_penguatan_das,
                'nama_pelaksana' => 'Muhamad Rizal Molou',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'V',
                'jabatan' => 'Pengendali Ekosistem Hutan Pemula',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_penguatan_das,
                'nama_pelaksana' => 'Muh. Aditya Alimuddin Baso',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'V',
                'jabatan' => 'Pengendali Ekosistem Hutan Pemula',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_penguatan_das,
                'nama_pelaksana' => 'Mohamad Eko Resaldy Suleman',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'V',
                'jabatan' => 'Pengendali Ekosistem Hutan Pemula',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_penguatan_das,
                'nama_pelaksana' => 'Rainan Alfonso',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'V',
                'jabatan' => 'Pengendali Ekosistem Hutan Pemula',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_penguatan_das,
                'nama_pelaksana' => 'Alimin S Takuwa, A.Md.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'VII',
                'jabatan' => 'Pengendali Ekosistem Hutan Terampil',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_penguatan_das,
                'nama_pelaksana' => 'Ismet Gani, A.Md.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'VII',
                'jabatan' => 'Pengendali Ekosistem Hutan Terampil',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_penguatan_das,
                'nama_pelaksana' => 'Sufandi Age, A.Md.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'VII',
                'jabatan' => 'Penyuluh Kehutanan Terampil',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_penguatan_das,
                'nama_pelaksana' => 'Abdulhalis Botutihe, S. TP.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'IX',
                'jabatan' => 'Pengendali Ekosistem Hutan Ahli Pertama',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_penguatan_das,
                'nama_pelaksana' => 'Yamin K. Lima, S.P.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'IX',
                'jabatan' => 'Penyuluh Kehutanan Ahli Pertama',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_penguatan_das,
                'nama_pelaksana' => 'Radi Afriandi E, S.Hut.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'IX',
                'jabatan' => 'Penyuluh Kehutanan Ahli Pertama',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_penguatan_das,
                'nama_pelaksana' => 'Mas Udin Adrian Hapulu, S.P.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'IX',
                'jabatan' => 'Penyuluh Kehutanan Ahli Pertama',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_penguatan_das,
                'nama_pelaksana' => 'Sri Putri Ayu Rezeki, S.Hut.',
                'jenis_kelamin' => 'P',
                'pangkat_golongan' => 'IX',
                'jabatan' => 'Pengendali Ekosistem Hutan Ahli Pertama',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_penguatan_das,
                'nama_pelaksana' => 'Yusran Lasantu, S.P.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'IX',
                'jabatan' => 'Penyuluh Kehutanan Ahli Pertama',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_penguatan_das,
                'nama_pelaksana' => 'Diky Aprilyanto Hunawa, S.Hut.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'IX',
                'jabatan' => 'Pengendali Ekosistem Hutan Ahli Pertama',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_penguatan_das,
                'nama_pelaksana' => 'Rahman Kadir, S.Hut.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'IX',
                'jabatan' => 'Penyuluh Kehutanan Ahli Pertama',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_penguatan_das,
                'nama_pelaksana' => 'Robinson Sahabi, S.Hut.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'IX',
                'jabatan' => 'Penyuluh Kehutanan Ahli Pertama',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_penguatan_das,
                'nama_pelaksana' => 'Yusran Adam, S.P.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'IX',
                'jabatan' => 'Penyuluh Kehutanan Ahli Pertama',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_penguatan_das,
                'nama_pelaksana' => 'Rizal Bano, S.P.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'IX',
                'jabatan' => 'Pengendali Ekosistem Hutan Ahli Pertama',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_penguatan_das,
                'nama_pelaksana' => 'Rizky Afriyanto Ente, S.Hut.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'IX',
                'jabatan' => 'Penyuluh Kehutanan Ahli Pertama',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_penguatan_das,
                'nama_pelaksana' => 'Abdul Rahmat Dai, S.Hut.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'IX',
                'jabatan' => 'Penyuluh Kehutanan Ahli Pertama',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_penguatan_das,
                'nama_pelaksana' => 'Muktar Dakio, S.Hut.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'IX',
                'jabatan' => 'Penyuluh Kehutanan Ahli Pertama',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_penguatan_das,
                'nama_pelaksana' => 'Siti Amalia Jafar, S.T.P.',
                'jenis_kelamin' => 'P',
                'pangkat_golongan' => 'IX',
                'jabatan' => 'Penyuluh Kehutanan Ahli Pertama',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_penguatan_das,
                'nama_pelaksana' => 'Ratna Batti\'\' Palummi\'\', S.Hut.',
                'jenis_kelamin' => 'P',
                'pangkat_golongan' => 'IX',
                'jabatan' => 'Penyuluh Kehutanan Ahli Pertama',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_penguatan_das,
                'nama_pelaksana' => 'Sahril U. Pontoh, S.P.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'IX',
                'jabatan' => 'Pengendali Ekosistem Hutan Ahli Pertama',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_penguatan_das,
                'nama_pelaksana' => 'Alifya Fatrisia Nur Hakim, S.Hut.',
                'jenis_kelamin' => 'P',
                'pangkat_golongan' => 'IX',
                'jabatan' => 'Penyuluh Kehutanan Ahli Pertama',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_penguatan_das,
                'nama_pelaksana' => 'Mega Sri Nurhalima Wolinelo, S.Hut.',
                'jenis_kelamin' => 'P',
                'pangkat_golongan' => 'IX',
                'jabatan' => 'Penyuluh Kehutanan Ahli Pertama',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_rhl,
                'nama_pelaksana' => 'Waode Faridawaty, S.Hut., M.Si.',
                'jenis_kelamin' => 'P',
                'pangkat_golongan' => 'III/d',
                'jabatan' => 'Kepala Seksi RHL',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_rhl,
                'nama_pelaksana' => 'Farid Widodo Sugiarto, S.Hut., M.P.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'III/d',
                'jabatan' => 'Analis Hutan dan Lahan Rehabilitasi Hutan dan Lahan',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_rhl,
                'nama_pelaksana' => 'Adhy Febrianto, S.Kom.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'III/c',
                'jabatan' => 'Analis Hutan dan Lahan Rehabilitasi Hutan dan Lahan',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_rhl,
                'nama_pelaksana' => 'Ariyanto R. Tangahu, S.Hut.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'III/b',
                'jabatan' => 'Pengendali Ekosistem Hutan Ahli Pertama',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_rhl,
                'nama_pelaksana' => 'Hendra Said',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'V',
                'jabatan' => 'Pengendali Ekosistem Hutan Pemula',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_rhl,
                'nama_pelaksana' => 'Dwi Intanirmala',
                'jenis_kelamin' => 'P',
                'pangkat_golongan' => 'V',
                'jabatan' => 'Pengendali Ekosistem Hutan Pemula',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_rhl,
                'nama_pelaksana' => 'Desi Ishak',
                'jenis_kelamin' => 'P',
                'pangkat_golongan' => 'V',
                'jabatan' => 'Pengendali Ekosistem Hutan Pemula',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_rhl,
                'nama_pelaksana' => 'Prabowo Payuyu',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'V',
                'jabatan' => 'Pengendali Ekosistem Hutan Pemula',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_rhl,
                'nama_pelaksana' => 'Jefri Moha, A.Md.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'VII',
                'jabatan' => 'Pengendali Ekosistem Hutan Terampil',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_rhl,
                'nama_pelaksana' => 'Yahya Nento, A.Md.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'VII',
                'jabatan' => 'Pengendali Ekosistem Hutan Terampil',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_rhl,
                'nama_pelaksana' => 'Samrun A. Kunuti, S.Hut.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'IX',
                'jabatan' => 'Pengendali Ekosistem Hutan Ahli Pertama',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_rhl,
                'nama_pelaksana' => 'Fatmah Razak Abdul, S.P.',
                'jenis_kelamin' => 'P',
                'pangkat_golongan' => 'IX',
                'jabatan' => 'Pengendali Ekosistem Hutan Ahli Pertama',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_rhl,
                'nama_pelaksana' => 'Abdul Gafur Daud, S.Hut.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'IX',
                'jabatan' => 'Pengendali Ekosistem Hutan Ahli Pertama',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_rhl,
                'nama_pelaksana' => 'Deliyanti Miolo, S.Hut.',
                'jenis_kelamin' => 'P',
                'pangkat_golongan' => 'IX',
                'jabatan' => 'Pengendali Ekosistem Hutan Ahli Pertama',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_rhl,
                'nama_pelaksana' => 'Aditya Warman, S.Hut.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'IX',
                'jabatan' => 'Pengendali Ekosistem Hutan Ahli Pertama',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_rhl,
                'nama_pelaksana' => 'Lia Yuliana Gani, S.Hut.',
                'jenis_kelamin' => 'P',
                'pangkat_golongan' => 'IX',
                'jabatan' => 'Pengendali Ekosistem Hutan Ahli Pertama',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_perencaanaa_evaluasi,
                'nama_pelaksana' => 'Dicky Artha, S.Hut.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'III/d',
                'jabatan' => 'Kepala Seksi Perencanaan dan Evaluasi DAS',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_perencaanaa_evaluasi,
                'nama_pelaksana' => 'Henddy Andriawan Kaipa, S.Hut.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'III/d',
                'jabatan' => 'Analis Hutan dan Lahan Rehabilitasi Hutan dan Lahan',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_perencaanaa_evaluasi,
                'nama_pelaksana' => 'Rifqi Muttaqin, S.Hut.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'III/b',
                'jabatan' => 'Pengendali Ekosistem Hutan Ahli Pertama',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_perencaanaa_evaluasi,
                'nama_pelaksana' => 'Tasrif',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'II/c',
                'jabatan' => 'Pengendali Ekosistem Hutan Terampil',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_perencaanaa_evaluasi,
                'nama_pelaksana' => 'Rahmat Muslim',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'II/b',
                'jabatan' => 'Pengendali Ekosistem Hutan Pemula',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_perencaanaa_evaluasi,
                'nama_pelaksana' => 'Suleman M Walangadi',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'V',
                'jabatan' => 'Pengendali Ekosistem Hutan Pemula',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_perencaanaa_evaluasi,
                'nama_pelaksana' => 'Imran Rahman, A.Md.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'VII',
                'jabatan' => 'Pengendali Ekosistem Hutan Terampil',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_perencaanaa_evaluasi,
                'nama_pelaksana' => 'Renol Halada, A.Md.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'VII',
                'jabatan' => 'Pengendali Ekosistem Hutan Terampil',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_perencaanaa_evaluasi,
                'nama_pelaksana' => 'Michael Iqbal Tontoiyo, A.Md.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'VII',
                'jabatan' => 'Pengendali Ekosistem Hutan Terampil',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_perencaanaa_evaluasi,
                'nama_pelaksana' => 'Cindrawati Tulen, A.Md.',
                'jenis_kelamin' => 'P',
                'pangkat_golongan' => 'VII',
                'jabatan' => 'Pengendali Ekosistem Hutan Terampil',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_perencaanaa_evaluasi,
                'nama_pelaksana' => 'Suleman Panto, A.Md',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'VII',
                'jabatan' => 'Pengendali Ekosistem Hutan Terampil',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_perencaanaa_evaluasi,
                'nama_pelaksana' => 'Lukman Mustaki, A.Md',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'VII',
                'jabatan' => 'Pengendali Ekosistem Hutan Terampil',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_perencaanaa_evaluasi,
                'nama_pelaksana' => 'Novriyanto Dwi Sapoetra, S.Hut.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'IX',
                'jabatan' => 'Pengendali Ekosistem Hutan Ahli Pertama',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_perencaanaa_evaluasi,
                'nama_pelaksana' => 'Muttaqin, S.P.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'IX',
                'jabatan' => 'Pengendali Ekosistem Hutan Ahli Pertama',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_perencaanaa_evaluasi,
                'nama_pelaksana' => 'Astria Hilipito, S.P.',
                'jenis_kelamin' => 'P',
                'pangkat_golongan' => 'IX',
                'jabatan' => 'Pengendali Ekosistem Hutan Ahli Pertama',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_perencaanaa_evaluasi,
                'nama_pelaksana' => 'Septriani Rombe, S.Hut.',
                'jenis_kelamin' => 'P',
                'pangkat_golongan' => 'IX',
                'jabatan' => 'Pengendali Ekosistem Hutan Ahli Pertama',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_perencaanaa_evaluasi,
                'nama_pelaksana' => 'Vindiawati Tontoiyo, S.Hut.',
                'jenis_kelamin' => 'P',
                'pangkat_golongan' => 'IX',
                'jabatan' => 'Pengendali Ekosistem Hutan Ahli Pertama',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => Str::ulid(),
                'seksi_id' => $seksi_perencaanaa_evaluasi,
                'nama_pelaksana' => 'Ricky Rahmat Nurkamiden, S.P.',
                'jenis_kelamin' => 'L',
                'pangkat_golongan' => 'IX',
                'jabatan' => 'Pengendali Ekosistem Hutan Ahli Pertama',
                'no_telp' => '',
                'instansi' => 'BPDAS Bone Bolango',
                'status_pegawai' => 'KLHK',
                'created_at' => now(),
                'updated_at' => now()
            ],


        ];

        // Masukkan data ke dalam tabel
        DB::table('employees')->insert($employees);
    }
}
